### ISSUE TITLE
Adding I2c grove Hum + temp

### ISSUE THREAD

**Issue by fabiendostie** [limengdu/mmwave-kit-external-components#10]
I have a simple question.
In the example on the [wiki where a Temperature + Humidity I2C grove is added to the kit. ](https://wiki.seeedstudio.com/mmWave_Kit_And_Grove_Connect_To_ESPHome/#jump) The tutorial tells me to add it as a **aht** sensor in the .yaml code
```
i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True
  id: bus_0x38
-------------------------------------------------------
sensor:
  - platform: aht10
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s
```

My issue is that the grove sensor itself is a [DHT20v2](https://www.seeedstudio.com/Grove-Temperature-Humidity-Sensor-V2-0-DHT20-p-4967.html#reviews)
shouldn't I be using [esphome's DHT temp+hum Sensor ](https://esphome.io/components/sensor/dht) instead?  If it's the case, what pins should I enter since for the DHT sensor 'pin' is a required option for [sensor.dht].

I get temp and humidity data using  ```- platform: aht10```, but the data seems wrong, temperature is way too high.

Thank you.

**Comment by limengdu** [comment]
Hi, according to the information you provided, you are using DHT20, so you should need to use the yaml code here.
https://esphome.io/components/sensor/aht10.html
The DHT code is using GPIO and the DHT20 is an IIC protocol.

**Comment by fabiendostie** [comment]
OK, so my .yaml is okay?
```
i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True
  id: bus_0x38
-------------------------------------------------------
sensor:
  - platform: aht10
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s
```

temperatures and humidity seems waaaaay off though. any idea why? Maybe the sensor should be outside the enclosure?
